version: "3.9"

services:
  db:
    image: postgres:15
    container_name: storage_postgres
    restart: always
    environment:
      POSTGRES_USER: user_name
      POSTGRES_PASSWORD: user_password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: storage_redis
    restart: always
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: storage_minio
    command: server /data --console-address ":9001"
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Web UI
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
